spring:
  application:
    name: kitchen-domain

  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:midterm-domain2}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      pool-name: KitchenDomainHikariCP

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:      
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      timeout: 2000
      # Add the following if you need auth
      # password: ${REDIS_PASSWORD:}

  # Kitchen Queue Configuration
  kitchen:
    queue:
      orders: kitchen-order-queue
      order-updates: order.status.updates.queue
    exchange:
      orders: restaurant.exchange
    routing-key:
      orders: kitchen.orders
      order-updates: kitchen.order.updates

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /kitchen
  forward-headers-strategy: framework
  tomcat:
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000
    keep-alive-timeout: 60000

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:rSp/kisYeCdda6X8j0HA6jYCcpevXe6LQe3wHTPTC7GP5bQ5gqN15cLkAhtVomGpmT08rSqoyiD1wRxFOGhg8A==}
    expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    root: INFO
    khuong.com.kitchendomain: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always